# Generated by Django 4.2.30 on 2026-06-20 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambulances', '0002_shift_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverassignment',
            name='ambulance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ambulances.ambulance'),
        ),
    ]
