# Generated by Django 4.2.30 on 2026-06-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulances', '0004_alter_driverassignment_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='contact',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
