# Generated by Django 4.2.30 on 2026-06-22 08:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ambulances', '0006_emergencyrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('ON_SITE', 'On Site'), ('TRANSPORTING', 'Transporting'), ('ARRIVED_HOSPITAL', 'Arrived at Hospital'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='ambulances.ambulance')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='ambulances.driver')),
                ('emergency_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='ambulances.emergencyrequest')),
            ],
        ),
    ]
