# Generated by Django 4.2.30 on 2026-06-28 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ambulances', '0007_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ambulance',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='ambulances', to='ambulances.equipment'),
        ),
    ]
