# Generated by Django 4.2.30 on 2026-07-04 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ambulances', '0008_equipment_ambulance_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='lifecycle_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('AT_INCIDENT', 'At Incident'), ('PATIENT_ONBOARD', 'Patient Onboard'), ('HOSPITAL_ARRIVAL', 'Hospital Arrival'), ('SANITIZATION', 'Sanitization'), ('READY', 'Ready')], default='AVAILABLE', max_length=50),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('AT_INCIDENT', 'At Incident'), ('PATIENT_ONBOARD', 'Patient Onboard'), ('HOSPITAL_ARRIVAL', 'Hospital Arrival'), ('SANITIZATION', 'Sanitization'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=50),
        ),
        migrations.CreateModel(
            name='AmbulanceLifecycleLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=50, null=True)),
                ('to_status', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_logs', to='ambulances.ambulance')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_actions', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_logs', to='ambulances.mission')),
            ],
        ),
    ]
