# Generated by Django 4.2.30 on 2026-07-13 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambulances', '0011_ambulance_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emergency_requests', to='ambulances.hospital'),
        ),
    ]
