# Generated by Django 4.2.30 on 2026-07-13 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulances', '0012_emergencyrequest_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='contact',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
