# Generated by Django 4.2.30 on 2026-07-14 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulances', '0013_alter_driver_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='contact_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='contact_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.CheckConstraint(check=models.Q(('contact__regex', '^[0-9]{10}$')), name='driver_contact_must_be_10_digits'),
        ),
        migrations.AddConstraint(
            model_name='emergencyrequest',
            constraint=models.CheckConstraint(check=models.Q(('contact_number__regex', '^[0-9]{10}$')), name='emergency_request_contact_number_must_be_10_digits'),
        ),
        migrations.AddConstraint(
            model_name='hospital',
            constraint=models.CheckConstraint(check=models.Q(('contact_number__regex', '^[0-9]{10}$')), name='hospital_contact_number_must_be_10_digits'),
        ),
    ]
